[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.44"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/www"
  to = "/"

[[redirects]]
  from = "/btnet/*"
  to = "http://btnet.ifdefined.com/btnet/:splat"